#include "./ConvertedImages/pika.h"
#include "./ConvertedImages/rainbowSwirl.h"
#include "./ConvertedImages/rickRoll.h"
#include "./ConvertedImages/UCR1.h"
#include "./ConvertedImages/UCR2.h"
#include "./ConvertedImages/wilcox.h"
